import {StyleSheet} from 'react-native';
import {fonts} from '../../../constants';

export const styles = StyleSheet.create({
  scroll_view: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  text_input: {
    marginTop: 20,
  },
  input_group: {
    width: '100%',
    paddingHorizontal: 15,
    borderBottomColor: '#E1E9F6',
    borderBottomWidth: 5,
    borderStyle: 'solid',
    paddingBottom: 30,
  },
  check: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginTop: 20,
  },
  check_box: {
    alignItems: 'center',
    width: 22,
    height: 22,
    justifyContent: 'center',
    marginRight: 12,
    borderRadius: 2,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#06B217',
  },
  check_box_text: {
    fontFamily: fonts.BE_VIETNAM_PRO_REGULAR,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    color: '#2C3442',
  },
  label_style: {
    fontFamily: fonts.BE_VIETNAM_PRO_SEMIBOLD,
    color: '#394B6A',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '600',
    textTransform: 'uppercase',
    opacity: 0.7,
  },
  input_style: {
    paddingVertical: 10,
    borderBottomColor: '#E1E9F6',
    borderBottomWidth: 1,
    borderStyle: 'solid',
    fontFamily: fonts.BE_VIETNAM_PRO_SEMIBOLD,
    fontSize: 14,
    fontWeight: '600',
    color: '#2C3442',
    backgroundColor: '#FFFFFF',
    paddingRight: 40,
  },
  icon_position: {
    position: 'absolute',
    bottom: 5,
    right: -10,
    padding: 10,
  },
  icon_style: {
    width: 14,
    height: 14,
  },
  fee_group: {
    width: '100%',
    paddingHorizontal: 15,
    marginTop: 25,
  },
  fee_group_select: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomColor: '#E1E9F6',
    borderBottomWidth: 1,
    borderStyle: 'solid',
    paddingBottom: 25,
  },
  select_box: {
    flexDirection: 'row',
    width: '68%',
    alignItems: 'center',
  },
  select_box_style: {
    fontFamily: fonts.BE_VIETNAM_PRO_REGULAR,
    fontWeight: '400',
    fontSize: 13,
    lineHeight: 18,
    color: '#2C3442',
    marginRight: 5,
  },
  fee_content: {
    fontFamily: fonts.BE_VIETNAM_PRO_REGULAR,
    fontWeight: '400',
    fontSize: 13,
    lineHeight: 18,
    color: '#2C3442',
    width: '28%',
    textAlign: 'right',
  },
  total: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
  },
  total_title: {
    fontFamily: fonts.BE_VIETNAM_PRO_SEMIBOLD,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    textTransform: 'uppercase',
    color: '#2C3442',
  },
  total_content: {
    fontFamily: fonts.BE_VIETNAM_PRO_BOLD,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    color: '#BF0000',
  },
  note: {
    marginTop: 10,
    width: '100%',
    padding: 15,
    backgroundColor: '#EFF2F8',
    borderRadius: 6,
  },
  note_title: {
    fontFamily: fonts.BE_VIETNAM_PRO_BOLD,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '700',
    color: '#BF0000',
    fontStyle: 'italic',
  },
  note_content: {
    fontFamily: fonts.BE_VIETNAM_PRO_REGULAR,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '400',
    color: '#2C3442',
    fontStyle: 'italic',
  },
  footer_style: {
    backgroundColor: '#FFFFFF',
  },
  input_text_style: {
    textAlign: 'left',
    marginHorizontal: 0,
    fontFamily: fonts.BE_VIETNAM_PRO_SEMIBOLD,
    color: '#394B6A',
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '600',
  },
  dropdownStyle: {
    borderRadius: 6,
  },
  rowStyle: {
    paddingHorizontal: 30,
  },
  rowTextStyle: {
    textAlign: 'left',
    marginHorizontal: 0,
    fontFamily: fonts.BE_VIETNAM_PRO_SEMIBOLD,
    color: '#394B6A',
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '600',
  },
  selectedRowTextStyle: {
    color: '#BF0000',
  },
  form_style: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 0,
    height: 'auto',
  },
  list_error: {
    fontFamily: fonts.BE_VIETNAM_PRO_SEMIBOLD,
    fontWeight: '600',
    fontSize: 10,
    lineHeight: 22,
    color: '#3C61EA',
    textTransform: 'uppercase',
    textDecorationLine: 'underline',
    textAlign: 'center',
  },
});
