import {StyleSheet} from 'react-native';
import {fonts} from '../../../constants';

export const styles = StyleSheet.create({
  scroll_view: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  session_top: {},
  group: {
    paddingHorizontal: 15,
    marginTop: 30,
  },
  group_title: {
    fontFamily: fonts.BE_VIETNAM_PRO_SEMIBOLD,
    color: '#394B6A',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  group_content: {
    paddingVertical: 10,
    borderBottomColor: '#E1E9F6',
    borderBottomWidth: 1,
    borderStyle: 'solid',
    fontFamily: fonts.BE_VIETNAM_PRO_SEMIBOLD,
    fontSize: 14,
    fontWeight: '600',
    color: '#2C3442',
  },
  session_bottom: {},
  address: {},
  title: {
    fontFamily: fonts.BE_VIETNAM_PRO_BOLD,
    color: '#2C3442',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    marginHorizontal: 15,
    marginTop: 35,
  },
  check: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
    paddingHorizontal: 15,
  },
  check_box: {
    alignItems: 'center',
    width: 22,
    height: 22,
    justifyContent: 'center',
    marginRight: 12,
    borderRadius: 2,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#AAB0AA',
    backgroundColor: '#AAB0AA',
  },
  check_box_text: {
    fontFamily: fonts.BE_VIETNAM_PRO_REGULAR,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    color: '#2C3442',
  },
  fee_group: {
    width: '100%',
    paddingHorizontal: 15,
    marginTop: 25,
  },
  note: {
    marginTop: 10,
    width: '100%',
    padding: 15,
    backgroundColor: '#EFF2F8',
    borderRadius: 6,
  },
  note_title: {
    fontFamily: fonts.BE_VIETNAM_PRO_BOLD,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '700',
    color: '#BF0000',
    fontStyle: 'italic',
  },
  note_content: {
    fontFamily: fonts.BE_VIETNAM_PRO_REGULAR,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '400',
    color: '#2C3442',
    fontStyle: 'italic',
  },
});
