import {StyleSheet} from 'react-native';
import {colors, fonts} from '../../../constants';

export const styles = StyleSheet.create({
  scroll_view: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  session_top: {
    paddingHorizontal: 15,
    borderBottomColor: '#E1E9F6',
    borderBottomWidth: 5,
  },
  input_picker: {
    flex: 1,
  },
  group: {
    marginTop: 30,
  },
  text_input: {
    marginTop: 20,
  },
  label_style: {
    fontFamily: fonts.BE_VIETNAM_PRO_SEMIBOLD,
    color: '#394B6A',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '600',
    textTransform: 'uppercase',
    opacity: 0.7,
  },
  error_message: {
    marginTop: 5,
  },
  dateItemWrapper: {
    flexDirection: 'row',
    gap: 15,
    marginTop: 30,
  },
  input_style: {
    paddingVertical: 10,
    borderBottomColor: '#E1E9F6',
    borderBottomWidth: 1,
    borderStyle: 'solid',
    fontFamily: fonts.BE_VIETNAM_PRO_SEMIBOLD,
    fontSize: 14,
    fontWeight: '600',
    color: '#2C3442',
    backgroundColor: '#FFFFFF',
    paddingRight: 40,
  },
  icon_position: {
    position: 'absolute',
    bottom: 5,
    right: -10,
    padding: 10,
  },
  icon_style: {
    width: 14,
    height: 14,
  },
  group_title: {
    fontFamily: fonts.BE_VIETNAM_PRO_SEMIBOLD,
    color: '#394B6A',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  group_content: {
    paddingVertical: 10,
    borderBottomColor: '#E1E9F6',
    borderBottomWidth: 1,
    borderStyle: 'solid',
    fontFamily: fonts.BE_VIETNAM_PRO_SEMIBOLD,
    fontSize: 14,
    fontWeight: '600',
    color: '#2C3442',
  },
  session_bottom: {
    paddingHorizontal: 15,
    marginTop: 20,
  },
  address: {},
  check: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  check_box: {
    alignItems: 'center',
    width: 22,
    height: 22,
    justifyContent: 'center',
    marginRight: 12,
    borderRadius: 2,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#AAB0AA',
    backgroundColor: '#AAB0AA',
  },
  check_box_text: {
    fontFamily: fonts.BE_VIETNAM_PRO_REGULAR,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    color: '#2C3442',
  },
  fee_group: {
    width: '100%',
    paddingHorizontal: 15,
    marginTop: 20,
  },
  note: {
    marginTop: 10,
    width: '100%',
    padding: 15,
    backgroundColor: '#EFF2F8',
    borderRadius: 6,
  },
  note_title: {
    fontFamily: fonts.BE_VIETNAM_PRO_BOLD,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '700',
    color: '#BF0000',
    fontStyle: 'italic',
  },
  note_content: {
    fontFamily: fonts.BE_VIETNAM_PRO_REGULAR,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '400',
    color: '#2C3442',
    fontStyle: 'italic',
  },
  list_error: {
    fontFamily: fonts.BE_VIETNAM_PRO_SEMIBOLD,
    fontWeight: '600',
    fontSize: 10,
    lineHeight: 22,
    color: '#3C61EA',
    textTransform: 'uppercase',
    textDecorationLine: 'underline',
    textAlign: 'center',
  },
  headerModalWrapper: {
    paddingVertical: 20,
    paddingHorizontal: 20,
    marginBottom: 20,
    borderBottomColor: colors.DARKER_BLUE,
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  textStyled: {
    color: colors.DARKER_BLUE,
    textTransform: 'uppercase',
    fontFamily: fonts.BE_VIETNAM_PRO_BOLD,
    fontSize: 14,
  },
  drop_down: {
    position: 'absolute',
    zIndex: 1,
    top: 50,
    width: '100%',
    borderBottomWidth: 1,
    borderBlockColor: colors.BLUE,
    height: 200,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.25,
    shadowRadius: 5.84,
    elevation: 10,
    backgroundColor: colors.WHITE,
  },
  drop_text: {
    color: '#2C3442',
    padding: 15,
    borderBottomColor: '#E1E9F6',
    borderBottomWidth: 1,
  },
});
