import {StyleSheet} from 'react-native';
import {fonts} from '../../constants';

export const styles = StyleSheet.create({
  scrollView: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  general: {
    paddingHorizontal: 15,
    paddingVertical: 20,
    borderBottomColor: '#F2F6FC',
    borderBottomWidth: 10,
  },
  title: {
    fontFamily: fonts.BE_VIETNAM_PRO_BOLD,
    fontSize: 12,
    lineHeight: 24,
    fontWeight: '700',
    textTransform: 'uppercase',
    color: '#0F6AA9',
  },
  general_content: {},
  general_group: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  general_group_title: {
    fontFamily: fonts.BE_VIETNAM_PRO_MEDIUM,
    fontSize: 10,
    lineHeight: 18,
    fontWeight: '500',
    color: '#394B6A',
    textTransform: 'uppercase',
  },
  general_group_content: {
    fontFamily: fonts.BE_VIETNAM_PRO_BOLD,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: '#394B6A',
  },
  general_group_left: {
    flexDirection: 'row',
    flex: 1,
    alignItems: 'center',
  },
  general_group_right: {
    fontFamily: fonts.BE_VIETNAM_PRO_MEDIUM,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '500',
    color: '#00A32E',
    paddingHorizontal: 13,
    paddingVertical: 4,
    backgroundColor: '#E2FFD9',
    borderRadius: 100,
    marginLeft: 50,
  },
  content: {
    paddingHorizontal: 15,
    paddingVertical: 20,
    borderBottomColor: '#F2F6FC',
    borderBottomWidth: 10,
  },
  content_box: {
    marginTop: 20,
    paddingBottom: 10,
    borderBottomColor: '#E1E9F6',
    borderBottomWidth: 1,
  },
  content_box_title: {
    fontFamily: fonts.BE_VIETNAM_PRO_BOLD,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '600',
    color: '#394B6A',
    textTransform: 'uppercase',
    opacity: 0.7,
    marginBottom: 10,
  },
  content_box_text: {
    fontFamily: fonts.BE_VIETNAM_PRO_MEDIUM,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '500',
    color: '#2C3442',
  },
  fee: {
    paddingHorizontal: 15,
    paddingVertical: 20,
  },
  fee_group: {
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  fee_group_left: {
    marginRight: 50,
    flex: 1,
    fontFamily: fonts.BE_VIETNAM_PRO_REGULAR,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '400',
    color: '#394B6A',
    opacity: 0.7,
  },
  fee_group_right: {
    fontFamily: fonts.BE_VIETNAM_PRO_MEDIUM,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '500',
    color: '#2C3442',
  },
  nullWrapper: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#394B6A',
    marginRight: 12,
  },
  nullText: {
    textAlign: 'center',
    fontFamily: fonts.BE_VIETNAM_PRO_REGULAR,
    fontSize: 9,
  },
});
