import {StyleSheet} from 'react-native';
import {fonts} from '../../constants';

export const styles = StyleSheet.create({
  icon: {
    width: 32,
    height: 32,
    marginRight: 10,
  },
  scroll_view: {
    flex: 1,
    backgroundColor: '#F7FAFF',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  group_content_time_right: {
    width: '28%',
    textAlign: 'right',
    flex: 1,
    fontFamily: fonts.BE_VIETNAM_PRO_REGULAR,
    fontSize: 13,
    lineHeight: 18,
    color: '#BF0000',
    fontWeight: '400',
    fontStyle: 'italic',
  },
  session: {
    paddingHorizontal: 15,
    paddingTop: 15,
    paddingBottom: 20,
    borderBottomColor: '#F2F6FC',
    borderBottomWidth: 10,
    borderStyle: 'solid',
    backgroundColor: '#FFFFFF',
  },
  group_image: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#F8FAFF',
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#C1E1F6',
    borderStyle: 'solid',
  },
  group_text: {
    fontFamily: fonts.BE_VIETNAM_PRO_REGULAR,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '400',
    color: '#2C3442',
    flex: 1,
  },
  group_content: {
    marginTop: 20,
  },
  group_content_time_left: {
    width: '68%',
    textAlign: 'left',
    flex: 1,
    fontFamily: fonts.BE_VIETNAM_PRO_REGULAR,
    fontSize: 13,
    lineHeight: 18,
    color: '#2C3442',
    fontWeight: '400',
  },
  group_content_title: {
    fontFamily: fonts.BE_VIETNAM_PRO_BOLD,
    fontSize: 12,
    lineHeight: 24,
    color: '#0F6AA9',
    fontWeight: '700',
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  group_content_license_plates: {
    fontFamily: fonts.BE_VIETNAM_PRO_BOLD,
    fontSize: 14,
    lineHeight: 20,
    color: '#2C3442',
    fontWeight: '700',
    marginBottom: 10,
  },
  license_plates: {
    fontFamily: fonts.BE_VIETNAM_PRO_MEDIUM,
    fontSize: 14,
    lineHeight: 18,
    color: '#394B6A',
    fontWeight: '500',
  },
  pass: {
    fontFamily: fonts.BE_VIETNAM_PRO_MEDIUM,
    fontSize: 11,
    lineHeight: 16,
    color: '#008334',
    fontWeight: '500',
    paddingHorizontal: 38,
    paddingVertical: 4,
    backgroundColor: '#BCEBCF',
    borderRadius: 100,
  },
  not_pass: {
    fontFamily: fonts.BE_VIETNAM_PRO_MEDIUM,
    fontSize: 11,
    lineHeight: 16,
    color: '#830000',
    fontWeight: '500',
    paddingHorizontal: 20,
    paddingVertical: 4,
    backgroundColor: '#FFD05B',
    borderRadius: 100,
  },
  group_content_time: {
    flex: 1,
    fontFamily: fonts.BE_VIETNAM_PRO_REGULAR,
    fontSize: 13,
    lineHeight: 18,
    color: '#2C3442',
    fontWeight: '400',
    flexDirection: 'row',
  },
  content: {
    backgroundColor: '#FFFFFF',
    paddingBottom: 20,
  },
  footer_style: {
    backgroundColor: '#FFFFFF',
  },
  title: {
    fontFamily: fonts.BE_VIETNAM_PRO_BOLD,
    fontSize: 12,
    lineHeight: 24,
    color: '#0F6AA9',
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  content_box: {
    marginTop: 20,
    paddingBottom: 10,
    borderBottomColor: '#E1E9F6',
    borderBottomWidth: 1,
  },
  content_box_title: {
    fontFamily: fonts.BE_VIETNAM_PRO_SEMIBOLD,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '600',
    color: '#394B6A',
    textTransform: 'uppercase',
    opacity: 0.7,
    marginBottom: 10,
  },
  content_box_text: {
    fontFamily: fonts.BE_VIETNAM_PRO_MEDIUM,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '500',
    color: '#2C3442',
  },
  addres: {
    fontFamily: fonts.BE_VIETNAM_PRO_MEDIUM,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '500',
    color: '#00A32E',
    paddingHorizontal: 13,
    paddingVertical: 4,
    backgroundColor: '#E2FFD9',
    borderRadius: 100,
  },
});
